### ISSUE TITLE
Save the output of .rank() to a pd

### ISSUE THREAD

**Issue by ThomasVenter** [samanemami/TOPSIS#1]
Love the package!

How do I save the .rank() output to a pd? I can print the tp.rank() but cant append as it comes as a single variable

**Comment by samanemami** [comment]
Hi, thanks 
tp.rank() is already a pd.DataFrame instance
If you want you can change it to arrays by using values ; `tp.rank().values`

**Comment by ThomasVenter** [comment]
What is the pd called? I am attempting to print the str of the recommended value without reading from the terminal. Sorry new to Python

**Comment by samanemami** [comment]
so try the;
```Python
print(tp.rank().values)
```

`pd` is the Pandas library
